name: mumax5
channels:
  - conda-forge
dependencies:
  # required
  - python=3.8
  - conda-build
  - pytest
  - matplotlib
  - numpy

  # code checks
  - black
  - cpplint
  - flake8
  - flake8-docstrings
  - isort # check that imports are in the right order
  - pre-commit
  - pip
  - pip:
      - clang-format

  # optional
  - ipython
