name: mumaxplus
channels:
  - conda-forge
  - defaults
  - bkryza/label/clang-uml  # for the UML diagrams in the documentation
dependencies:
  # required
  - python=3.13
  - conda-build
  - pytest
  - pytest-repeat
  - matplotlib
  - numpy
  - cmake=4.0.0
  - scipy

  # code checks
  - black
  - cpplint
  - flake8
  - flake8-docstrings
  - isort # check that imports are in the right order
  - pre-commit
  - pip

  # optional
  - ipython
  - jupyter
  - ipywidgets
  - pyvista
  - pillow  # should be contained in matplotlib
  - pandas

  # documentation generation
  - sphinx
  - sphinx-book-theme
  - numpydoc
  - sphinxcontrib-video
  - sphinx-copybutton
  - sphinx-design
  - clang-uml

  # pip blocks
  - pip:
      - clang-format            # code checks
      - pyovf                   # optional
      - sphinxcontrib.plantuml  # documentation generation
